# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rokas M.
tagline:          'Computer Graphics'
description:      'A place to showcase my work'
url:              https://github.com/malukasrokas
baseurl:          /

author:
  name:           'Rokas Malukas'
  url:            https://github.com/malukasrokas

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
